project_name: SMUAIC25
exp_name: OriPimVit
use_wandb: False
wandb_entity: professional_team
train_root: /root/autodl-tmp/AICtrain/train5000
val_root: ~
val_split: 0.1
test_root:  /root/autodl-tmp/AICtest/test5000
data_size: 384
num_workers: 2
batch_size: 64
model_name: vit
pretrained: ~
optimizer: SGD
max_lr: 0.0005
wdecay: 0.0005
max_epochs: 20
warmup_batchs: 800
use_amp: True
use_fpn: True
fpn_size: 768
use_selection: True
num_classes: 5000
num_selects: 
  layer1: 512
  layer2: 256
  layer3: 128
  layer4: 32
use_combiner: True
lambda_b: 0.5
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 4
log_freq: 100
eval_freq: 1
save_dir: /root/autodl-tmp/FGVC-PIM-master/records/